version: 2

project_name: anilix

before:
  hooks:
    - go mod tidy

builds:
  - id: desktop
    binary: anilix

    env:
      - CGO_ENABLED=0

    ldflags:
      - -s -w -X github.com/hishantik/anilix/version.Version={{ .Version }}

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64

    ignore:
      - goos: windows
        goarch: arm64

  - id: termux
    binary: anilix

    env:
      - CGO_ENABLED=0

    ldflags:
      - -s -w -X github.com/hishantik/anilix/version.Version={{ .Version }}

    goos:
      - android

    goarch:
      - arm64

archives:
  - id: desktop-archive
    ids:
      - desktop

    formats:
      - tar.gz

    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: termux-archive
    ids:
      - termux

    formats:
      - tar.gz

    name_template: >-
      {{ .ProjectName }}_termux_{{ .Arch }}

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ .Version }}-dev"

changelog:
  sort: asc
